version: '3'
services:
  paris-reverseproxy:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/paris-open/reverseproxy:5.0.0-SNAPSHOT
    volumes:
      - /home/tmorbagalh/platoon-dev/certificate:/etc/cert/
#      - c:/etc/idscert/localhost:/etc/cert/
    ports:
    - "443:443" # IDS-HTTP API

  paris-core:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/paris-open/core:5.0.0-JKS
    volumes:
      - /home/tmorbagalh/platoon-dev/certificate:/etc/cert/
#      - c:/etc/idscert/localhost:/etc/cert/
    restart: always
    environment:
    - SPARQL_ENDPOINT=http://paris-fuseki:3030/connectorData
    - ELASTICSEARCH_HOSTNAME=paris-elasticsearch
    - SHACL_VALIDATION=true
    - DAPS_VALIDATE_INCOMING=false
    - IDENTITY_JAVAKEYSTORE=/etc/cert/isstbroker-keystore.jks
    - COMPONENT_URI=https://localhost/
    - COMPONENT_CATALOGURI=https://localhost/catalog/
    expose:
    - "8080"

  paris-fuseki:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/paris-open/fuseki:5.0.0-SNAPSHOT
    volumes:
      - paris-fuseki:/fuseki
    expose:
    - "3030"

volumes:
    paris-fuseki:
